# Generated by Django 4.2 on 2026-04-19 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('potential_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
